### ISSUE TITLE
Add a paper on stability analysis and efficient Shapley Values computation for LLMs; Add a mini-tutorial on RASP-based Mechanistic Interpretability; 

### ISSUE THREAD

**Issue by yangalan123** [ruizheliUOA/Awesome-Interpretability-in-Large-Language-Models#5]
Hi, 

Thanks for contributing to this great list by compiling so many resources! I just want to (shamelessly) self-promote some of my own contributions to the interpretability field:

1. Add a paper on stability analysis on Shapley Values applied on LLMs and efficient Shapley Values computation for LLMs
(I personally call it as "Amortized Interpretability" :-) )

> Yang, C., Yin, F., He, H., Chang, K. W., Ma, X., & Xiang, B. (2023, July). Efficient Shapley Values Estimation by Amortization for Text Classification. In Proceedings of the 61st Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers) (pp. 8666-8680).
[paper](https://arxiv.org/abs/2305.19998), [code](https://github.com/yangalan123/Amortized-Interpretability), [video](https://www.youtube.com/watch?v=CsCRU8Hzpms)

2. Add a mini-tutorial on RASP-based Mechanistic Interpretability, at TTIC & UChicago NLP Seminar [slides](https://docs.google.com/presentation/d/1oIPHP_7qjsrnrDb3kdZIUZt-wQofkiQl/edit?usp=sharing&ouid=111912319459945992784&rtpof=true&sd=true)

Let me know if there are further questions or concerns! 

Best,
Chenghao

**Comment by ruizheliUOA** [comment]
No problem, and I have added to the list
